---
# Source: elasticsearch/templates/cluster.yaml
apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: elasticsearch-cluster
  namespace: logging
  labels:
    app: elasticsearch
spec:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.3
  cerebro:
    image: upmcenterprises/cerebro:0.6.8
  elastic-search-image: "upmcenterprises/docker-elasticsearch-kubernetes:6.1.3_0"
  client-node-replicas: 2
  master-node-replicas: 3
  data-node-replicas: 2
  network-host: 0.0.0.0
  zones: []
  data-volume-size: 1Gi
  java-options: -Xms256m -Xmx256m
  snapshot:
    scheduler-enabled: false
    bucket-name: elasticsnapshots
    cron-schedule: "@every 2m"
    image: "upmcenterprises/elasticsearch-cron:0.0.3"
  use-ssl: true
  storage:
    storage-class: gp2
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
